// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BeginRest():Promise<void>;

export function BeginWork():Promise<void>;

export function GetConfigMinutes():Promise<main.Config>;

export function MoreWork(arg1:number):Promise<void>;

export function Skip():Promise<void>;

export function SkipRest():Promise<void>;

export function SkipWork():Promise<void>;

export function StartSession(arg1:number,arg2:number):Promise<void>;

export function Stop():Promise<void>;
