// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginRest() {
  return window['go']['main']['App']['BeginRest']();
}

export function BeginWork() {
  return window['go']['main']['App']['BeginWork']();
}

export function GetConfigMinutes() {
  return window['go']['main']['App']['GetConfigMinutes']();
}

export function MoreWork(arg1) {
  return window['go']['main']['App']['MoreWork'](arg1);
}

export function SkipRest() {
  return window['go']['main']['App']['SkipRest']();
}

export function SkipWork() {
  return window['go']['main']['App']['SkipWork']();
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
